# Ensures packages build correctly
name: Build Packages

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Yarn
        run: |
          npm install -g yarn
          echo "Yarn version: $(yarn -v)"
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:packages
