name: Deploy docs to GitHub Pages

on:
  push:
    branches: ["docs"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Yarn
        run: |
          npm install -g yarn
          echo "Yarn version: $(yarn -v)"
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc
      - name: Install Dependencies
        run: yarn install --frozen-lockfile && cd docs && yarn install --frozen-lockfile
      - name: Build Packages
        run: yarn build:packages
      - name: Create Docs
        run: yarn build:docs
      - name: Fix permissions
        run: |
          chmod -c -R +rX "./docs/build" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/build
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
